### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by adaxi** [Fllorent0D/ha-custom-component-pluxee-be#7]
I wanted to have my Pluxee balance displayed in Home Assistant. I proceeded to install the custom component via HACS.
Unfortunately the latest release of the component (0.1.3) fails to contact the sodexo4you.be host. 

```
2024-07-31 21:17:30.387 DEBUG (MainThread) [custom_components.sodexo.api] Logging in...
2024-07-31 21:17:30.441 ERROR (MainThread) [custom_components.sodexo.api] Cannot connect to host sodexo4you.be:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)')]
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1149, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1182, in _create_connection_transport
    await waiter
  File "/usr/local/lib/python3.12/asyncio/sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
  File "/usr/local/lib/python3.12/asyncio/sslproto.py", line 560, in _do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.12/ssl.py", line 917, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1000)
```

After looking around in the repository I found out that a new library was used to support the new name (Sodexo to Pluxee).
I had to figure out how to configure HACS to pull the main branch instead of 0.1.3, once I did this, the custom component seemed to work flawlessly.

I created this ticket to ask if it was possible to make a new release of the component. This would:
- Save some time for the next person installing the component.
- Remove the annoying warning indicating that I need to update to version 0.1.3.

**Comment by michaelvandorpe** [comment]
I bumped into the same issue, and I tried the suggested workaround to install from the main branch, but either that is not available anymore in hacs, or I cannot find how to do it… 

Any plans to update the version in hacs to account for the new Pluxee name?

thanks!

**Comment by jessedobbelaere** [comment]
The issue is downstream in this library: https://github.com/Tib612/pluxee-api/issues/3

**Comment by Tib612** [comment]
Hi @Fllorent0D, this issue has been solved in #8 .
Could you release a new version with a new tag? As using this repo in HACS still uses your old code.

Thanks.
